symfonycasts_reset_password:
  # Replace symfonycasts.reset_password.fake_request_repository with the full
  # namespace of the request repository after it has been created.
  # I.e. App\Repository\ResetPasswordRequestRepository
  request_password_repository: symfonycasts.reset_password.fake_request_repository